---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: istio-mirror
spec:
  ports:
  - name: service-b
    port: 8080
    targetPort: 80
  selector:
    app: service-b
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: istio-mirror
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - image: nginx
        name: service-b
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 20m
            memory: 5Mi
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: service-b-config
      volumes:
        - name: service-b-config
          configMap:
            name: service-b
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-b
  namespace: istio-mirror
data:
  index.html: "Welcome to service-b!"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service-b
  namespace: istio-mirror
spec:
  hosts:
  - "service-b"
  http:
    - route:
      - destination:
          host: service-b
        weight: 100
      mirror:
        host: service-c
      mirror_percent: 100
