---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: istio-mirror
spec:
  ports:
  - name: service-a
    port: 8080
    targetPort: 80
  selector:
    app: service-a
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: istio-mirror
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - image: nginx
        name: service-a
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 20m
            memory: 5Mi
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: service-a-config
      volumes:
        - name: service-a-config
          configMap:
            name: service-a
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-a
  namespace: istio-mirror
data:
  index.html: "Welcome to Service-A!"